main1: main1.o connettwk.o dynamics.o 
	g++ main1.o connettwk.o dynamics.o -o main1 -std=c++11

main1.o: main1.cpp
	g++ -c main1.cpp -std=c++11

connettwk.o: connettwk.cpp
	g++ -c connettwk.cpp -std=c++11

dynamics.o: dynamics.cpp
	g++ -c dynamics.cpp -std=c++11
	
clean:
	rm *.o main1


# main2Rand_slurm: main2Rand_slurm.o connettwk.o dynamics.o 
# 	g++ main2Rand_slurm.o connettwk.o dynamics.o -o main2Rand_slurm -std=c++11

# main2Rand_slurm.o: main2Rand_slurm.cpp
# 	g++ -c main2Rand_slurm.cpp -std=c++11

# connettwk.o: connettwk.cpp
# 	g++ -c connettwk.cpp -std=c++11

# dynamics.o: dynamics.cpp
# 	g++ -c dynamics.cpp -std=c++11
	
# clean:
# 	rm *.o main2Rand_slurm






# main2Rand: main2Rand.o connettwk.o dynamics.o 
# 	g++ main2Rand.o connettwk.o dynamics.o -o main2Rand -std=c++11

# main2Rand.o: main2Rand.cpp
# 	g++ -c main2Rand.cpp -std=c++11

# connettwk.o: connettwk.cpp
# 	g++ -c connettwk.cpp -std=c++11

# dynamics.o: dynamics.cpp
# 	g++ -c dynamics.cpp -std=c++11
	
# clean:
# 	rm *.o main2Rand